### PR TITLE
Change all paths to absolute #52

### PR DESCRIPTION
**Pull request by IsidoreHouaga**
Change all paths to absolute #52

### CODE REVIEW

**Comment by IsidoreHouaga** [comment]
@janaobsteter Are these changes ok? Specifically should we change only `../{project}/` to `{workdir}/` or also `../project/` to `{workdir}/`

**Comment by janaobsteter** [comment]
@IsidoreHouaga , in the new version, there is no more "../Project" because we've merged in the PR

**Comment by janaobsteter** [comment]
But you can change all of them to the new version

**Comment by IsidoreHouaga** [comment]
@janaobsteter ok but which change is correct?  ../{project}/ to {workdir}/ or ../project/ to {workdir}/

**Pull request closed without merging**
